// Phần hiển thị thêm CHỈ cho 50 bộ thủ thông dụng (xem COMMON_RADICAL_IDS):
// tên tiếng Việt ("bộ Nhân") + emoji minh họa. Các bộ còn lại không có 2 field này.
export interface RadicalDetail {
  name: string;
  emoji: string;
}

export const RADICAL_DETAILS: Record<number, RadicalDetail> = {
  9: { name: 'bộ Nhân', emoji: '🧍' },
  18: { name: 'bộ Đao', emoji: '🔪' },
  19: { name: 'bộ Lực', emoji: '💪' },
  30: { name: 'bộ Khẩu', emoji: '👄' },
  31: { name: 'bộ Vi', emoji: '🔲' },
  32: { name: 'bộ Thổ', emoji: '🟫' },
  37: { name: 'bộ Đại', emoji: '🐘' },
  38: { name: 'bộ Nữ', emoji: '👩' },
  40: { name: 'bộ Miên', emoji: '🏠' },
  46: { name: 'bộ Sơn', emoji: '⛰️' },
  50: { name: 'bộ Cân', emoji: '🧣' },
  53: { name: 'bộ Nghiễm', emoji: '🏛️' },
  60: { name: 'bộ Xích', emoji: '🚶' },
  61: { name: 'bộ Tâm', emoji: '❤️' },
  64: { name: 'bộ Thủ', emoji: '✋' },
  66: { name: 'bộ Phộc', emoji: '✊' },
  72: { name: 'bộ Nhật', emoji: '☀️' },
  75: { name: 'bộ Mộc', emoji: '🌳' },
  85: { name: 'bộ Thủy', emoji: '💧' },
  86: { name: 'bộ Hỏa', emoji: '🔥' },
  93: { name: 'bộ Ngưu', emoji: '🐂' },
  94: { name: 'bộ Khuyển', emoji: '🐕' },
  96: { name: 'bộ Ngọc', emoji: '💎' },
  102: { name: 'bộ Điền', emoji: '🟩' },
  104: { name: 'bộ Bệnh', emoji: '🤒' },
  109: { name: 'bộ Mục', emoji: '👁️' },
  112: { name: 'bộ Thạch', emoji: '🪨' },
  115: { name: 'bộ Hòa', emoji: '🌾' },
  118: { name: 'bộ Trúc', emoji: '🎋' },
  119: { name: 'bộ Mễ', emoji: '🍚' },
  120: { name: 'bộ Mịch', emoji: '🧵' },
  130: { name: 'bộ Nhục', emoji: '🍖' },
  140: { name: 'bộ Thảo', emoji: '🌿' },
  142: { name: 'bộ Trùng', emoji: '🐛' },
  145: { name: 'bộ Y', emoji: '👕' },
  149: { name: 'bộ Ngôn', emoji: '💬' },
  154: { name: 'bộ Bối', emoji: '🐚' },
  157: { name: 'bộ Túc', emoji: '🦶' },
  159: { name: 'bộ Xa', emoji: '🚗' },
  162: { name: 'bộ Sước', emoji: '👣' },
  163: { name: 'bộ Ấp', emoji: '🏘️' },
  167: { name: 'bộ Kim', emoji: '🥇' },
  169: { name: 'bộ Môn', emoji: '🚪' },
  170: { name: 'bộ Phụ', emoji: '🏔️' },
  173: { name: 'bộ Vũ', emoji: '🌧️' },
  181: { name: 'bộ Hiệt', emoji: '📄' },
  184: { name: 'bộ Thực', emoji: '🍽️' },
  187: { name: 'bộ Mã', emoji: '🐎' },
  195: { name: 'bộ Ngư', emoji: '🐟' },
  196: { name: 'bộ Điểu', emoji: '🐦' },
};
