// 214 BỘ THỦ KHANG HY (部首) — kèm pinyin, tên Hán-Việt, nghĩa tiếng Việt, số nét.
// `zh`: dạng chính (phồn thể Khang Hy); `alt`: biến thể giản thể / dạng đứng cạnh chữ.
export interface RadicalEntry {
  id: number;
  zh: string;
  alt?: string;
  py: string;
  hv: string;
  vi: string;
  strokes: number;
  /** Chỉ có ở 50 bộ thông dụng (xem radical-details.data.ts): tên tiếng Việt + emoji minh họa. */
  name?: string;
  emoji?: string;
}

export const RADICALS: RadicalEntry[] = [
  { id: 1, zh: '一', py: 'yī', hv: 'nhất', vi: 'một', strokes: 1 },
  { id: 2, zh: '丨', py: 'gǔn', hv: 'cổn', vi: 'nét sổ', strokes: 1 },
  { id: 3, zh: '丶', py: 'zhǔ', hv: 'chủ', vi: 'điểm, chấm', strokes: 1 },
  { id: 4, zh: '丿', py: 'piě', hv: 'phiệt', vi: 'nét phẩy', strokes: 1 },
  { id: 5, zh: '乙', py: 'yǐ', hv: 'ất', vi: 'can thứ hai; nét cong', strokes: 1 },
  { id: 6, zh: '亅', py: 'jué', hv: 'quyết', vi: 'nét móc', strokes: 1 },
  { id: 7, zh: '二', py: 'èr', hv: 'nhị', vi: 'hai', strokes: 2 },
  { id: 8, zh: '亠', py: 'tóu', hv: 'đầu', vi: 'cái nắp, đầu', strokes: 2 },
  { id: 9, zh: '人', alt: '亻', py: 'rén', hv: 'nhân', vi: 'người', strokes: 2 },
  { id: 10, zh: '儿', py: 'ér', hv: 'nhi', vi: 'trẻ con, chân', strokes: 2 },
  { id: 11, zh: '入', py: 'rù', hv: 'nhập', vi: 'vào', strokes: 2 },
  { id: 12, zh: '八', py: 'bā', hv: 'bát', vi: 'tám', strokes: 2 },
  { id: 13, zh: '冂', py: 'jiōng', hv: 'quynh', vi: 'khung, vây quanh', strokes: 2 },
  { id: 14, zh: '冖', py: 'mì', hv: 'mịch', vi: 'khăn phủ, nắp', strokes: 2 },
  { id: 15, zh: '冫', py: 'bīng', hv: 'băng', vi: 'nước đá', strokes: 2 },
  { id: 16, zh: '几', py: 'jī', hv: 'kỷ', vi: 'cái ghế; mấy', strokes: 2 },
  { id: 17, zh: '凵', py: 'kǎn', hv: 'khảm', vi: 'cái hố, miệng há', strokes: 2 },
  { id: 18, zh: '刀', alt: '刂', py: 'dāo', hv: 'đao', vi: 'con dao', strokes: 2 },
  { id: 19, zh: '力', py: 'lì', hv: 'lực', vi: 'sức mạnh', strokes: 2 },
  { id: 20, zh: '勹', py: 'bāo', hv: 'bao', vi: 'bao bọc', strokes: 2 },
  { id: 21, zh: '匕', py: 'bǐ', hv: 'chủy', vi: 'cái thìa', strokes: 2 },
  { id: 22, zh: '匚', py: 'fāng', hv: 'phương', vi: 'cái hộp, tủ', strokes: 2 },
  { id: 23, zh: '匸', py: 'xì', hv: 'hệ', vi: 'che đậy', strokes: 2 },
  { id: 24, zh: '十', py: 'shí', hv: 'thập', vi: 'mười', strokes: 2 },
  { id: 25, zh: '卜', py: 'bǔ', hv: 'bốc', vi: 'bói toán', strokes: 2 },
  { id: 26, zh: '卩', py: 'jié', hv: 'tiết', vi: 'đốt tre, con dấu', strokes: 2 },
  { id: 27, zh: '厂', py: 'hǎn', hv: 'hán', vi: 'sườn núi; xưởng', strokes: 2 },
  { id: 28, zh: '厶', py: 'sī', hv: 'tư', vi: 'riêng tư', strokes: 2 },
  { id: 29, zh: '又', py: 'yòu', hv: 'hựu', vi: 'lại, nữa', strokes: 2 },
  { id: 30, zh: '口', py: 'kǒu', hv: 'khẩu', vi: 'miệng', strokes: 3 },
  { id: 31, zh: '囗', py: 'wéi', hv: 'vi', vi: 'vây quanh', strokes: 3 },
  { id: 32, zh: '土', py: 'tǔ', hv: 'thổ', vi: 'đất', strokes: 3 },
  { id: 33, zh: '士', py: 'shì', hv: 'sĩ', vi: 'học trò, quan', strokes: 3 },
  { id: 34, zh: '夂', py: 'zhǐ', hv: 'truy', vi: 'đến sau, đi chậm', strokes: 3 },
  { id: 35, zh: '夊', py: 'suī', hv: 'tuy', vi: 'bước đi', strokes: 3 },
  { id: 36, zh: '夕', py: 'xī', hv: 'tịch', vi: 'chiều tối', strokes: 3 },
  { id: 37, zh: '大', py: 'dà', hv: 'đại', vi: 'to lớn', strokes: 3 },
  { id: 38, zh: '女', py: 'nǚ', hv: 'nữ', vi: 'con gái, đàn bà', strokes: 3 },
  { id: 39, zh: '子', py: 'zǐ', hv: 'tử', vi: 'con', strokes: 3 },
  { id: 40, zh: '宀', py: 'mián', hv: 'miên', vi: 'mái nhà', strokes: 3 },
  { id: 41, zh: '寸', py: 'cùn', hv: 'thốn', vi: 'tấc', strokes: 3 },
  { id: 42, zh: '小', py: 'xiǎo', hv: 'tiểu', vi: 'nhỏ', strokes: 3 },
  { id: 43, zh: '尢', py: 'yóu', hv: 'vưu', vi: 'què chân', strokes: 3 },
  { id: 44, zh: '尸', py: 'shī', hv: 'thi', vi: 'xác chết, thân thể', strokes: 3 },
  { id: 45, zh: '屮', py: 'chè', hv: 'triệt', vi: 'mầm non', strokes: 3 },
  { id: 46, zh: '山', py: 'shān', hv: 'sơn', vi: 'núi', strokes: 3 },
  { id: 47, zh: '巛', alt: '川', py: 'chuān', hv: 'xuyên', vi: 'sông', strokes: 3 },
  { id: 48, zh: '工', py: 'gōng', hv: 'công', vi: 'việc, thợ', strokes: 3 },
  { id: 49, zh: '己', py: 'jǐ', hv: 'kỷ', vi: 'bản thân', strokes: 3 },
  { id: 50, zh: '巾', py: 'jīn', hv: 'cân', vi: 'khăn', strokes: 3 },
  { id: 51, zh: '干', py: 'gān', hv: 'can', vi: 'khô; làm', strokes: 3 },
  { id: 52, zh: '幺', py: 'yāo', hv: 'yêu', vi: 'nhỏ, út', strokes: 3 },
  { id: 53, zh: '广', py: 'guǎng', hv: 'nghiễm', vi: 'mái nhà rộng', strokes: 3 },
  { id: 54, zh: '廴', py: 'yǐn', hv: 'dẫn', vi: 'bước dài', strokes: 3 },
  { id: 55, zh: '廾', py: 'gǒng', hv: 'củng', vi: 'chắp tay', strokes: 3 },
  { id: 56, zh: '弋', py: 'yì', hv: 'dặc', vi: 'cái cọc', strokes: 3 },
  { id: 57, zh: '弓', py: 'gōng', hv: 'cung', vi: 'cái cung', strokes: 3 },
  { id: 58, zh: '彐', py: 'jì', hv: 'ký', vi: 'mõm, đầu (thú)', strokes: 3 },
  { id: 59, zh: '彡', py: 'shān', hv: 'sam', vi: 'lông dài, râu', strokes: 3 },
  { id: 60, zh: '彳', py: 'chì', hv: 'xích', vi: 'bước chân trái', strokes: 3 },
  { id: 61, zh: '心', alt: '忄', py: 'xīn', hv: 'tâm', vi: 'tim, lòng', strokes: 4 },
  { id: 62, zh: '戈', py: 'gē', hv: 'qua', vi: 'cái giáo', strokes: 4 },
  { id: 63, zh: '戶', alt: '户', py: 'hù', hv: 'hộ', vi: 'cửa', strokes: 4 },
  { id: 64, zh: '手', alt: '扌', py: 'shǒu', hv: 'thủ', vi: 'tay', strokes: 4 },
  { id: 65, zh: '支', py: 'zhī', hv: 'chi', vi: 'cành', strokes: 4 },
  { id: 66, zh: '攴', alt: '攵', py: 'pū', hv: 'phộc', vi: 'đánh khẽ', strokes: 4 },
  { id: 67, zh: '文', py: 'wén', hv: 'văn', vi: 'văn, chữ', strokes: 4 },
  { id: 68, zh: '斗', py: 'dǒu', hv: 'đấu', vi: 'cái đấu (đong)', strokes: 4 },
  { id: 69, zh: '斤', py: 'jīn', hv: 'cân', vi: 'cái rìu; cân', strokes: 4 },
  { id: 70, zh: '方', py: 'fāng', hv: 'phương', vi: 'vuông, phía', strokes: 4 },
  { id: 71, zh: '无', py: 'wú', hv: 'vô', vi: 'không', strokes: 4 },
  { id: 72, zh: '日', py: 'rì', hv: 'nhật', vi: 'mặt trời, ngày', strokes: 4 },
  { id: 73, zh: '曰', py: 'yuē', hv: 'viết', vi: 'nói rằng', strokes: 4 },
  { id: 74, zh: '月', py: 'yuè', hv: 'nguyệt', vi: 'mặt trăng, tháng', strokes: 4 },
  { id: 75, zh: '木', py: 'mù', hv: 'mộc', vi: 'cây, gỗ', strokes: 4 },
  { id: 76, zh: '欠', py: 'qiàn', hv: 'khiếm', vi: 'ngáp; thiếu', strokes: 4 },
  { id: 77, zh: '止', py: 'zhǐ', hv: 'chỉ', vi: 'dừng lại', strokes: 4 },
  { id: 78, zh: '歹', py: 'dǎi', hv: 'đãi', vi: 'xấu, chết chóc', strokes: 4 },
  { id: 79, zh: '殳', py: 'shū', hv: 'thù', vi: 'cái giáo; đánh', strokes: 4 },
  { id: 80, zh: '毋', py: 'wú', hv: 'vô', vi: 'chớ, đừng', strokes: 4 },
  { id: 81, zh: '比', py: 'bǐ', hv: 'tỷ', vi: 'so sánh', strokes: 4 },
  { id: 82, zh: '毛', py: 'máo', hv: 'mao', vi: 'lông', strokes: 4 },
  { id: 83, zh: '氏', py: 'shì', hv: 'thị', vi: 'họ', strokes: 4 },
  { id: 84, zh: '气', py: 'qì', hv: 'khí', vi: 'hơi, khí', strokes: 4 },
  { id: 85, zh: '水', alt: '氵', py: 'shuǐ', hv: 'thủy', vi: 'nước', strokes: 4 },
  { id: 86, zh: '火', alt: '灬', py: 'huǒ', hv: 'hỏa', vi: 'lửa', strokes: 4 },
  { id: 87, zh: '爪', py: 'zhǎo', hv: 'trảo', vi: 'móng vuốt', strokes: 4 },
  { id: 88, zh: '父', py: 'fù', hv: 'phụ', vi: 'cha', strokes: 4 },
  { id: 89, zh: '爻', py: 'yáo', hv: 'hào', vi: 'hào (quẻ dịch)', strokes: 4 },
  { id: 90, zh: '爿', py: 'qiáng', hv: 'tường', vi: 'tấm ván, một nửa', strokes: 4 },
  { id: 91, zh: '片', py: 'piàn', hv: 'phiến', vi: 'mảnh, tấm', strokes: 4 },
  { id: 92, zh: '牙', py: 'yá', hv: 'nha', vi: 'răng', strokes: 4 },
  { id: 93, zh: '牛', alt: '牜', py: 'niú', hv: 'ngưu', vi: 'trâu, bò', strokes: 4 },
  { id: 94, zh: '犬', alt: '犭', py: 'quǎn', hv: 'khuyển', vi: 'chó', strokes: 4 },
  { id: 95, zh: '玄', py: 'xuán', hv: 'huyền', vi: 'đen huyền, sâu xa', strokes: 5 },
  { id: 96, zh: '玉', alt: '王', py: 'yù', hv: 'ngọc', vi: 'ngọc', strokes: 5 },
  { id: 97, zh: '瓜', py: 'guā', hv: 'qua', vi: 'quả dưa', strokes: 5 },
  { id: 98, zh: '瓦', py: 'wǎ', hv: 'ngõa', vi: 'ngói', strokes: 5 },
  { id: 99, zh: '甘', py: 'gān', hv: 'cam', vi: 'ngọt', strokes: 5 },
  { id: 100, zh: '生', py: 'shēng', hv: 'sinh', vi: 'sinh đẻ, sống', strokes: 5 },
  { id: 101, zh: '用', py: 'yòng', hv: 'dụng', vi: 'dùng', strokes: 5 },
  { id: 102, zh: '田', py: 'tián', hv: 'điền', vi: 'ruộng', strokes: 5 },
  { id: 103, zh: '疋', py: 'pǐ', hv: 'thất', vi: 'tấm vải', strokes: 5 },
  { id: 104, zh: '疒', py: 'nè', hv: 'bệnh', vi: 'bệnh tật', strokes: 5 },
  { id: 105, zh: '癶', py: 'bō', hv: 'bát', vi: 'gạt chân, bước', strokes: 5 },
  { id: 106, zh: '白', py: 'bái', hv: 'bạch', vi: 'trắng', strokes: 5 },
  { id: 107, zh: '皮', py: 'pí', hv: 'bì', vi: 'da', strokes: 5 },
  { id: 108, zh: '皿', py: 'mǐn', hv: 'mãnh', vi: 'bát đĩa', strokes: 5 },
  { id: 109, zh: '目', py: 'mù', hv: 'mục', vi: 'mắt', strokes: 5 },
  { id: 110, zh: '矛', py: 'máo', hv: 'mâu', vi: 'cái mâu', strokes: 5 },
  { id: 111, zh: '矢', py: 'shǐ', hv: 'thỉ', vi: 'mũi tên', strokes: 5 },
  { id: 112, zh: '石', py: 'shí', hv: 'thạch', vi: 'đá', strokes: 5 },
  { id: 113, zh: '示', alt: '礻', py: 'shì', hv: 'thị', vi: 'chỉ thị, cúng tế', strokes: 5 },
  { id: 114, zh: '禸', py: 'róu', hv: 'nhựu', vi: 'vết chân thú', strokes: 5 },
  { id: 115, zh: '禾', py: 'hé', hv: 'hòa', vi: 'lúa', strokes: 5 },
  { id: 116, zh: '穴', py: 'xué', hv: 'huyệt', vi: 'hang', strokes: 5 },
  { id: 117, zh: '立', py: 'lì', hv: 'lập', vi: 'đứng', strokes: 5 },
  { id: 118, zh: '竹', alt: '⺮', py: 'zhú', hv: 'trúc', vi: 'tre', strokes: 6 },
  { id: 119, zh: '米', py: 'mǐ', hv: 'mễ', vi: 'gạo', strokes: 6 },
  { id: 120, zh: '糸', alt: '糹 纟', py: 'mì', hv: 'mịch', vi: 'sợi tơ', strokes: 6 },
  { id: 121, zh: '缶', py: 'fǒu', hv: 'phẫu', vi: 'đồ sành', strokes: 6 },
  { id: 122, zh: '网', alt: '罒 ⺲', py: 'wǎng', hv: 'võng', vi: 'lưới', strokes: 6 },
  { id: 123, zh: '羊', alt: '⺶', py: 'yáng', hv: 'dương', vi: 'dê, cừu', strokes: 6 },
  { id: 124, zh: '羽', py: 'yǔ', hv: 'vũ', vi: 'lông vũ', strokes: 6 },
  { id: 125, zh: '老', alt: '耂', py: 'lǎo', hv: 'lão', vi: 'già', strokes: 6 },
  { id: 126, zh: '而', py: 'ér', hv: 'nhi', vi: 'mà, và', strokes: 6 },
  { id: 127, zh: '耒', py: 'lěi', hv: 'lỗi', vi: 'cái cày', strokes: 6 },
  { id: 128, zh: '耳', py: 'ěr', hv: 'nhĩ', vi: 'tai', strokes: 6 },
  { id: 129, zh: '聿', alt: '⺻', py: 'yù', hv: 'duật', vi: 'cái bút', strokes: 6 },
  { id: 130, zh: '肉', alt: '月', py: 'ròu', hv: 'nhục', vi: 'thịt', strokes: 6 },
  { id: 131, zh: '臣', py: 'chén', hv: 'thần', vi: 'bầy tôi', strokes: 6 },
  { id: 132, zh: '自', py: 'zì', hv: 'tự', vi: 'tự mình', strokes: 6 },
  { id: 133, zh: '至', py: 'zhì', hv: 'chí', vi: 'đến', strokes: 6 },
  { id: 134, zh: '臼', py: 'jiù', hv: 'cữu', vi: 'cái cối', strokes: 6 },
  { id: 135, zh: '舌', py: 'shé', hv: 'thiệt', vi: 'lưỡi', strokes: 6 },
  { id: 136, zh: '舛', py: 'chuǎn', hv: 'suyễn', vi: 'trái ngược', strokes: 6 },
  { id: 137, zh: '舟', py: 'zhōu', hv: 'chu', vi: 'thuyền', strokes: 6 },
  { id: 138, zh: '艮', py: 'gèn', hv: 'cấn', vi: 'quẻ Cấn; dừng', strokes: 6 },
  { id: 139, zh: '色', py: 'sè', hv: 'sắc', vi: 'màu sắc', strokes: 6 },
  { id: 140, zh: '艸', alt: '艹', py: 'cǎo', hv: 'thảo', vi: 'cỏ', strokes: 6 },
  { id: 141, zh: '虍', py: 'hū', hv: 'hổ', vi: 'vằn hổ', strokes: 6 },
  { id: 142, zh: '虫', py: 'chóng', hv: 'trùng', vi: 'sâu bọ', strokes: 6 },
  { id: 143, zh: '血', py: 'xuè', hv: 'huyết', vi: 'máu', strokes: 6 },
  { id: 144, zh: '行', py: 'xíng', hv: 'hành', vi: 'đi, làm', strokes: 6 },
  { id: 145, zh: '衣', alt: '衤', py: 'yī', hv: 'y', vi: 'áo', strokes: 6 },
  { id: 146, zh: '襾', py: 'yà', hv: 'á', vi: 'che phủ', strokes: 6 },
  { id: 147, zh: '見', alt: '见', py: 'jiàn', hv: 'kiến', vi: 'trông thấy', strokes: 7 },
  { id: 148, zh: '角', py: 'jiǎo', hv: 'giác', vi: 'sừng, góc', strokes: 7 },
  { id: 149, zh: '言', alt: '讠', py: 'yán', hv: 'ngôn', vi: 'lời nói', strokes: 7 },
  { id: 150, zh: '谷', py: 'gǔ', hv: 'cốc', vi: 'thung lũng; ngũ cốc', strokes: 7 },
  { id: 151, zh: '豆', py: 'dòu', hv: 'đậu', vi: 'đậu', strokes: 7 },
  { id: 152, zh: '豕', py: 'shǐ', hv: 'thỉ', vi: 'lợn', strokes: 7 },
  { id: 153, zh: '豸', py: 'zhì', hv: 'trãi', vi: 'loài báo, thú dữ', strokes: 7 },
  { id: 154, zh: '貝', alt: '贝', py: 'bèi', hv: 'bối', vi: 'vỏ sò; tiền của', strokes: 7 },
  { id: 155, zh: '赤', py: 'chì', hv: 'xích', vi: 'đỏ', strokes: 7 },
  { id: 156, zh: '走', alt: '赱', py: 'zǒu', hv: 'tẩu', vi: 'đi, chạy', strokes: 7 },
  { id: 157, zh: '足', alt: '⻊', py: 'zú', hv: 'túc', vi: 'chân', strokes: 7 },
  { id: 158, zh: '身', py: 'shēn', hv: 'thân', vi: 'thân thể', strokes: 7 },
  { id: 159, zh: '車', alt: '车', py: 'chē', hv: 'xa', vi: 'xe', strokes: 7 },
  { id: 160, zh: '辛', py: 'xīn', hv: 'tân', vi: 'cay; cực nhọc', strokes: 7 },
  { id: 161, zh: '辰', py: 'chén', hv: 'thìn', vi: 'giờ Thìn; ngày giờ', strokes: 7 },
  { id: 162, zh: '辵', alt: '辶', py: 'chuò', hv: 'sước', vi: 'chợt đi chợt dừng (bộ sước)', strokes: 7 },
  { id: 163, zh: '邑', alt: '阝 (phải)', py: 'yì', hv: 'ấp', vi: 'vùng đất, ấp', strokes: 7 },
  { id: 164, zh: '酉', py: 'yǒu', hv: 'dậu', vi: 'giờ Dậu; rượu', strokes: 7 },
  { id: 165, zh: '釆', py: 'biàn', hv: 'biện', vi: 'phân biệt', strokes: 7 },
  { id: 166, zh: '里', py: 'lǐ', hv: 'lý', vi: 'dặm; làng', strokes: 7 },
  { id: 167, zh: '金', alt: '钅', py: 'jīn', hv: 'kim', vi: 'vàng, kim loại', strokes: 8 },
  { id: 168, zh: '長', alt: '长', py: 'cháng', hv: 'trường', vi: 'dài', strokes: 8 },
  { id: 169, zh: '門', alt: '门', py: 'mén', hv: 'môn', vi: 'cửa', strokes: 8 },
  { id: 170, zh: '阜', alt: '阝 (trái)', py: 'fù', hv: 'phụ', vi: 'gò đất', strokes: 8 },
  { id: 171, zh: '隶', py: 'dài', hv: 'đãi', vi: 'kịp; đầy tớ', strokes: 8 },
  { id: 172, zh: '隹', py: 'zhuī', hv: 'truy', vi: 'chim đuôi ngắn', strokes: 8 },
  { id: 173, zh: '雨', py: 'yǔ', hv: 'vũ', vi: 'mưa', strokes: 8 },
  { id: 174, zh: '青', py: 'qīng', hv: 'thanh', vi: 'xanh', strokes: 8 },
  { id: 175, zh: '非', py: 'fēi', hv: 'phi', vi: 'sai, không', strokes: 8 },
  { id: 176, zh: '面', py: 'miàn', hv: 'diện', vi: 'mặt', strokes: 9 },
  { id: 177, zh: '革', py: 'gé', hv: 'cách', vi: 'da thuộc', strokes: 9 },
  { id: 178, zh: '韋', alt: '韦', py: 'wéi', hv: 'vi', vi: 'da thuộc', strokes: 9 },
  { id: 179, zh: '韭', py: 'jiǔ', hv: 'cửu', vi: 'rau hẹ', strokes: 9 },
  { id: 180, zh: '音', py: 'yīn', hv: 'âm', vi: 'âm thanh', strokes: 9 },
  { id: 181, zh: '頁', alt: '页', py: 'yè', hv: 'hiệt', vi: 'đầu; trang', strokes: 9 },
  { id: 182, zh: '風', alt: '风', py: 'fēng', hv: 'phong', vi: 'gió', strokes: 9 },
  { id: 183, zh: '飛', alt: '飞', py: 'fēi', hv: 'phi', vi: 'bay', strokes: 9 },
  { id: 184, zh: '食', alt: '飠 饣', py: 'shí', hv: 'thực', vi: 'ăn', strokes: 9 },
  { id: 185, zh: '首', py: 'shǒu', hv: 'thủ', vi: 'đầu', strokes: 9 },
  { id: 186, zh: '香', py: 'xiāng', hv: 'hương', vi: 'thơm', strokes: 9 },
  { id: 187, zh: '馬', alt: '马', py: 'mǎ', hv: 'mã', vi: 'ngựa', strokes: 10 },
  { id: 188, zh: '骨', py: 'gǔ', hv: 'cốt', vi: 'xương', strokes: 10 },
  { id: 189, zh: '高', py: 'gāo', hv: 'cao', vi: 'cao', strokes: 10 },
  { id: 190, zh: '髟', py: 'biāo', hv: 'tiêu', vi: 'tóc dài', strokes: 10 },
  { id: 191, zh: '鬥', alt: '斗', py: 'dòu', hv: 'đấu', vi: 'đánh nhau', strokes: 10 },
  { id: 192, zh: '鬯', py: 'chàng', hv: 'sưởng', vi: 'rượu nếp tế', strokes: 10 },
  { id: 193, zh: '鬲', py: 'gé', hv: 'cách', vi: 'cái đỉnh, nồi', strokes: 10 },
  { id: 194, zh: '鬼', py: 'guǐ', hv: 'quỷ', vi: 'ma quỷ', strokes: 10 },
  { id: 195, zh: '魚', alt: '鱼', py: 'yú', hv: 'ngư', vi: 'cá', strokes: 11 },
  { id: 196, zh: '鳥', alt: '鸟', py: 'niǎo', hv: 'điểu', vi: 'chim', strokes: 11 },
  { id: 197, zh: '鹵', alt: '卤', py: 'lǔ', hv: 'lỗ', vi: 'muối', strokes: 11 },
  { id: 198, zh: '鹿', py: 'lù', hv: 'lộc', vi: 'hươu', strokes: 11 },
  { id: 199, zh: '麥', alt: '麦', py: 'mài', hv: 'mạch', vi: 'lúa mạch', strokes: 11 },
  { id: 200, zh: '麻', py: 'má', hv: 'ma', vi: 'gai; tê', strokes: 11 },
  { id: 201, zh: '黃', alt: '黄', py: 'huáng', hv: 'hoàng', vi: 'vàng', strokes: 12 },
  { id: 202, zh: '黍', py: 'shǔ', hv: 'thử', vi: 'lúa nếp', strokes: 12 },
  { id: 203, zh: '黑', py: 'hēi', hv: 'hắc', vi: 'đen', strokes: 12 },
  { id: 204, zh: '黹', py: 'zhǐ', hv: 'chỉ', vi: 'thêu', strokes: 12 },
  { id: 205, zh: '黽', alt: '黾', py: 'mǐn', hv: 'mãnh', vi: 'ếch; cố gắng', strokes: 13 },
  { id: 206, zh: '鼎', py: 'dǐng', hv: 'đỉnh', vi: 'cái đỉnh', strokes: 13 },
  { id: 207, zh: '鼓', py: 'gǔ', hv: 'cổ', vi: 'cái trống', strokes: 13 },
  { id: 208, zh: '鼠', py: 'shǔ', hv: 'thử', vi: 'chuột', strokes: 13 },
  { id: 209, zh: '鼻', py: 'bí', hv: 'tỵ', vi: 'mũi', strokes: 14 },
  { id: 210, zh: '齊', alt: '齐', py: 'qí', hv: 'tề', vi: 'đều, ngang bằng', strokes: 14 },
  { id: 211, zh: '齒', alt: '齿', py: 'chǐ', hv: 'xỉ', vi: 'răng', strokes: 15 },
  { id: 212, zh: '龍', alt: '龙', py: 'lóng', hv: 'long', vi: 'rồng', strokes: 16 },
  { id: 213, zh: '龜', alt: '龟', py: 'guī', hv: 'quy', vi: 'rùa', strokes: 16 },
  { id: 214, zh: '龠', py: 'yuè', hv: 'dược', vi: 'ống sáo', strokes: 17 },
];
