// Nghĩa TIẾNG VIỆT thủ công cho các từ HSK 1–4 (HSK 3.0).
// - Key: chữ giản thể (zh). Value: nghĩa tiếng Việt ngắn gọn.
// - Các từ chưa có ở đây sẽ hiển thị nghĩa tiếng Anh (trường `en`) ở frontend.
// - Sau khi sửa file này, chạy lại script sinh data:
//     node scripts/gen-hsk-data.mjs   (xem scripts/README.md)
// Đóng góp thêm bản dịch rất được hoan nghênh!
export const VI_DICT: Record<string, string> = {
  // ===== HSK 1 (cốt lõi) =====
  '你好': 'xin chào',
  '你': 'bạn',
  '爱': 'yêu',
  '爱好': 'sở thích',
  '八': 'tám',
  '爸爸': 'bố, ba',
  '吧': 'nhé, nhỉ (trợ từ)',
  '白': 'trắng',
  '白天': 'ban ngày',
  '百': 'trăm',
  '班': 'lớp học',
  '半': 'một nửa',
  '包': 'túi, gói',
  '包子': 'bánh bao',
  '杯': 'cốc, ly (lượng từ)',
  '杯子': 'cái cốc, cái ly',
  '北京': 'Bắc Kinh',
  '本': 'quyển, cái (lượng từ sách vở)',
  '比': 'so với',
  '笔': 'bút',
  '笔记本': 'vở ghi chép',
  '边': 'bên, phía',
  '便宜': 'rẻ',
  '表': 'đồng hồ, bảng biểu',
  '别': 'đừng',
  '别的': 'khác',
  '别人': 'người khác',
  '宾馆': 'khách sạn',
  '病': 'bệnh, ốm',
  '病人': 'bệnh nhân',
  '不': 'không',
  '不客气': 'không có gì',
  '不用': 'không cần',
  '菜': 'món ăn, rau',
  '茶': 'trà',
  '差': 'kém, thiếu',
  '常常': 'thường xuyên',
  '唱歌': 'hát',
  '出': 'ra, đi ra',
  '出租车': 'taxi',
  '船': 'thuyền, tàu thủy',
  '次': 'lần, lượt (lượng từ)',
  '从': 'từ',
  '错': 'sai',
  '打电话': 'gọi điện thoại',
  '打篮球': 'chơi bóng rổ',
  '大': 'to, lớn',
  '大家': 'mọi người',
  '但是': 'nhưng',
  '到': 'đến',
  '的': 'của (trợ từ)',
  '得': '(trợ từ bổ ngữ)',
  '灯': 'đèn',
  '等': 'đợi, chờ',
  '弟弟': 'em trai',
  '点': 'giờ, điểm',
  '电影': 'phim',
  '电视': 'ti-vi',
  '电子邮件': 'thư điện tử, email',
  '东西': 'đồ vật',
  '懂': 'hiểu',
  '都': 'đều',
  '读': 'đọc',
  '对': 'đúng',
  '对不起': 'xin lỗi',
  '多': 'nhiều',
  '多少': 'bao nhiêu',
  '饿': 'đói',
  '儿子': 'con trai',
  '耳朵': 'tai',
  '二': 'hai',
  '饭': 'cơm, bữa ăn',
  '饭店': 'nhà hàng',
  '房间': 'phòng',
  '非常': 'rất, vô cùng',
  '飞机': 'máy bay',
  '分': 'phút',
  '分钟': 'phút',
  '高兴': 'vui vẻ',
  '高': 'cao',
  '哥哥': 'anh trai',
  '个': 'cái (lượng từ chung)',
  '给': 'cho',
  '跟': 'cùng, với',
  '工作': 'công việc, làm việc',
  '狗': 'con chó',
  '汉语': 'tiếng Hán, tiếng Trung',
  '好吃': 'ngon',
  '号': 'số, ngày (trong tháng)',
  '喝': 'uống',
  '和': 'và',
  '很': 'rất',
  '后面': 'phía sau',
  '孩子': 'đứa trẻ',
  '汉字': 'chữ Hán',
  '好': 'tốt, khỏe',
  '黑': 'đen',
  '黑板': 'bảng đen',
  '红': 'đỏ',
  '欢迎': 'hoan nghênh',
  '火车': 'tàu hỏa',
  '机场': 'sân bay',
  '鸡蛋': 'trứng gà',
  '几': 'mấy',
  '家': 'nhà, gia đình',
  '件': 'chiếc (lượng từ quần áo)',
  '教室': 'phòng học',
  '姐姐': 'chị gái',
  '介绍': 'giới thiệu',
  '今年': 'năm nay',
  '今天': 'hôm nay',
  '九': 'chín',
  '旧': 'cũ',
  '觉得': 'cảm thấy',
  '叫': 'gọi là, kêu',
  '教': 'dạy',
  '脚': 'chân',
  '接': 'đón',
  '街': 'phố',
  '节日': 'lễ hội',
  '结婚': 'kết hôn',
  '结束': 'kết thúc',
  '紧张': 'hồi hộp, căng thẳng',
  '进': 'vào',
  '近': 'gần',
  '京剧': 'kinh kịch',
  '酒': 'rượu',
  '就': 'thì, liền',
  '开车': 'lái xe',
  '看': 'xem, nhìn',
  '看病': 'khám bệnh',
  '看见': 'nhìn thấy',
  '块': 'tệ, miếng (lượng từ tiền)',
  '快': 'nhanh',
  '快乐': 'vui vẻ',
  '筷子': 'đũa',
  '来': 'đến, tới',
  '蓝': '(màu) xanh dương',
  '篮球': 'bóng rổ',
  '老': 'già',
  '老师': 'giáo viên',
  '了': 'rồi (trợ từ)',
  '累': 'mệt',
  '冷': 'lạnh',
  '离': 'cách',
  '历史': 'lịch sử',
  '脸': 'mặt',
  '练习': 'luyện tập',
  '辆': 'chiếc (lượng từ xe)',
  '零': 'số không',
  '六': 'sáu',
  '楼': 'lầu, tầng',
  '路': 'đường',
  '妈妈': 'mẹ',
  '吗': 'không (trợ từ hỏi)',
  '买': 'mua',
  '卖': 'bán',
  '满意': 'hài lòng',
  '米': 'mét, gạo',
  '面条': 'mì sợi',
  '名字': 'tên',
  '明白': 'hiểu rõ',
  '明年': 'năm sau',
  '明天': 'ngày mai',
  '哪': 'nào',
  '哪儿': 'đâu, ở đâu',
  '那': 'kia, đó',
  '那个': 'cái kia',
  '那里': 'chỗ kia',
  '奶奶': 'bà nội',
  '男': 'nam',
  '男孩': 'bé trai',
  '南方': 'miền Nam',
  '难': 'khó',
  '呢': 'chứ, còn (trợ từ)',
  '能': 'có thể',
  '你们': 'các bạn',
  '年': 'năm',
  '您': 'ngài (kính ngữ)',
  '牛奶': 'sữa bò',
  '女': 'nữ',
  '女儿': 'con gái',
  '女孩': 'bé gái',
  '努力': 'nỗ lực',
  '爬山': 'leo núi',
  '盘子': 'cái đĩa',
  '旁边': 'bên cạnh',
  '跑步': 'chạy bộ',
  '票': 'vé',
  '漂亮': 'xinh đẹp',
  '苹果': 'quả táo',
  '七': 'bảy',
  '妻子': 'vợ',
  '起床': 'thức dậy',
  '千': 'nghìn',
  '签证': 'visa, thị thực',
  '前面': 'phía trước',
  '钱': 'tiền',
  '钱包': 'ví tiền',
  '亲爱': 'thân yêu',
  '清楚': 'rõ ràng',
  '晴': 'trời nắng',
  '去': 'đi',
  '去年': 'năm ngoái',
  '让': 'để, khiến',
  '热': 'nóng',
  '人们': 'mọi người',
  '认识': 'quen biết',
  '认真': 'nghiêm túc',
  '日': 'ngày, mặt trời',
  '肉': 'thịt',
  '三': 'ba',
  '商店': 'cửa hàng',
  '上': 'trên',
  '上班': 'đi làm',
  '上课': 'vào học',
  '上网': 'lên mạng',
  '生气': 'tức giận',
  '生日': 'sinh nhật',
  '什么': 'gì, cái gì',
  '十': 'mười',
  '时间': 'thời gian',
  '时候': 'lúc, khi',
  '事情': 'việc, sự việc',
  '手表': 'đồng hồ đeo tay',
  '手机': 'điện thoại di động',
  '谁': 'ai',
  '水果': 'hoa quả',
  '睡觉': 'ngủ',
  '说': 'nói',
  '司机': 'tài xế',
  '四': 'bốn',
  '岁': 'tuổi',
  '他': 'anh ấy, ông ấy',
  '她': 'cô ấy, bà ấy',
  '太': 'quá, lắm',
  '天天': 'hằng ngày',
  '天气': 'thời tiết',
  '甜': 'ngọt',
  '条': 'con (lượng từ vật dài)',
  '跳舞': 'nhảy múa',
  '听': 'nghe',
  '听说': 'nghe nói',
  '同学': 'bạn học',
  '图书馆': 'thư viện',
  '外面': 'bên ngoài',
  '玩': 'chơi',
  '晚上': 'buổi tối',
  '万': 'vạn (mười nghìn)',
  '完': 'xong',
  '碗': 'bát',
  '网球': 'quần vợt',
  '忘记': 'quên',
  '问': 'hỏi',
  '我': 'tôi',
  '我们': 'chúng tôi',
  '五': 'năm (số 5)',
  '午饭': 'bữa trưa',
  '西': 'phía tây',
  '西瓜': 'dưa hấu',
  '喜欢': 'thích',
  '现在': 'bây giờ',
  '香蕉': 'chuối',
  '相机': 'máy ảnh',
  '想': 'muốn, nhớ',
  '向': 'hướng về',
  '像': 'giống',
  '小时': 'giờ đồng hồ',
  '小姐': 'cô (gọi)',
  '些': 'một vài',
  '写': 'viết',
  '谢谢': 'cảm ơn',
  '星期': 'tuần',
  '休息': 'nghỉ ngơi',
  '学生': 'học sinh',
  '学习': 'học tập',
  '学校': 'trường học',
  '眼睛': 'mắt',
  '衣服': 'quần áo',
  '医生': 'bác sĩ',
  '医院': 'bệnh viện',
  '一': 'một',
  '一共': 'tổng cộng',
  '一会儿': 'một lát',
  '一起': 'cùng nhau',
  '一下': 'một chút',
  '一样': 'giống nhau',
  '以前': 'trước đây',
  '以为': 'cho rằng',
  '音乐': 'âm nhạc',
  '银行': 'ngân hàng',
  '应该': 'nên',
  '影响': 'ảnh hưởng',
  '用': 'dùng',
  '游戏': 'trò chơi',
  '有名': 'nổi tiếng',
  '有时候': 'đôi khi',
  '有意思': 'thú vị',
  '右边': 'phía phải',
  '雨': 'mưa',
  '语言': 'ngôn ngữ',
  '月': 'tháng, mặt trăng',
  '越': 'càng',
  '运动': 'thể thao',
  '在': 'ở, tại',
  '再见': 'tạm biệt',
  '早': 'sớm',
  '早上': 'buổi sáng',
  '怎么': 'thế nào',
  '站': 'trạm, đứng',
  '丈夫': 'chồng',
  '找': 'tìm',
  '这': 'đây, này',
  '这个': 'cái này',
  '这里': 'chỗ này',
  '着': '(trợ từ tiếp diễn)',
  '真': 'thật',
  '正在': 'đang',
  '知道': 'biết',
  '中国': 'Trung Quốc',
  '中午': 'buổi trưa',
  '中学': 'trường cấp 2',
  '中文': 'tiếng Trung',
  '重要': 'quan trọng',
  '住': 'ở, sống',
  '准备': 'chuẩn bị',
  '桌子': 'cái bàn',
  '字母': 'chữ cái',
  '最': 'nhất',
  '最近': 'gần đây',
  '昨天': 'hôm qua',
  '左边': 'phía trái',
  '坐': 'ngồi',
  '做': 'làm',
  '作业': 'bài tập',
  // ===== HSK 2 thường gặp =====
  '啊': '(cảm thán) à, a',
  '爱情': 'tình yêu',
  '爱人': 'vợ/chồng',
  '报纸': 'báo (giấy)',
  '北方': 'miền Bắc',
  '被': 'bị, được (câu bị động)',
  '鼻子': 'mũi',
  '比较': 'so sánh, khá là',
  '比赛': 'thi đấu',
  '必须': 'nhất định phải',
  '变化': 'thay đổi',
  '不但': 'không những',
  '菜单': 'thực đơn',
  '参加': 'tham gia',
  '草': 'cỏ',
  '层': 'tầng, lớp (lượng từ)',
  '长': 'dài',
  '衬衫': 'áo sơ mi',
  '成绩': 'thành tích',
  '城市': 'thành phố',
  '迟到': 'đến muộn',
  '出现': 'xuất hiện',
  '厨房': 'nhà bếp',
  '除了': 'ngoài... ra',
  '聪明': 'thông minh',
  '打扫': 'quét dọn',
  '打算': 'dự định',
  '带': 'mang, dẫn',
  '担心': 'lo lắng',
  '蛋糕': 'bánh gato',
  '当然': 'đương nhiên',
  '地': '(trợ từ trạng ngữ)',
  '低': 'thấp',
  '地方': 'nơi, chỗ',
  '地铁': 'tàu điện ngầm',
  '地图': 'bản đồ',
  '电梯': 'thang máy',
  '冬': 'mùa đông',
  '动物': 'động vật',
  '短': 'ngắn',
  '段': 'đoạn (lượng từ)',
  '锻炼': 'rèn luyện',
  '多么': 'biết bao',
  '而且': 'hơn nữa',
  '发烧': 'sốt',
  '发现': 'phát hiện',
  '方便': 'tiện lợi',
  '放': 'đặt, thả',
  '放心': 'yên tâm',
  '分开': 'tách ra',
  '丰富': 'phong phú',
  '附近': 'gần đây, lân cận',
  '复习': 'ôn tập',
  '干净': 'sạch sẽ',
  '敢': 'dám',
  '感冒': 'cảm cúm',
  '刚才': 'vừa nãy',
  '根据': 'căn cứ',
  '公园': 'công viên',
  '故事': 'câu chuyện',
  '刮风': 'nổi gió',
  '关': 'đóng, tắt',
  '关系': 'quan hệ',
  '关心': 'quan tâm',
  '关于': 'về, liên quan đến',
  '国家': 'quốc gia',
  '过': 'qua (trợ từ kinh nghiệm)',
  '号码': 'số (điện thoại)',
  '护照': 'hộ chiếu',
  '花': 'hoa, tiêu (tiền)',
  '画': 'vẽ, bức tranh',
  '坏': 'hỏng, xấu',
  '还': 'còn, vẫn',
  '环境': 'môi trường',
  '换': 'đổi',
  '黄': 'vàng',
  '回答': 'trả lời',
  '会议': 'hội nghị',
  '或者': 'hoặc',
  '几乎': 'hầu như',
  '机会': 'cơ hội',
  '极': 'cực kỳ',
  '记得': 'nhớ',
  '季节': 'mùa',
  '坚持': 'kiên trì',
  '简单': 'đơn giản',
  '见面': 'gặp mặt',
  '健康': 'khỏe mạnh',
  '讲': 'giảng, kể',
  '角': 'góc, hào (tiền)',
  '街道': 'phố',
  '节目': 'tiết mục, chương trình',
  '解决': 'giải quyết',
  '借': 'mượn',
  '经常': 'thường xuyên',
  '经过': 'đi qua, trải qua',
  '经理': 'giám đốc',
  '酒店': 'khách sạn',
  '举': 'giơ, tổ chức',
  '决定': 'quyết định',
  '咖啡': 'cà phê',
  '渴': 'khát',
  '刻': 'khắc (15 phút)',
  '客人': 'khách',
  '空调': 'điều hòa',
  '口': 'miệng, cái (lượng từ người nhà)',
  '哭': 'khóc',
  '裤子': 'quần dài',
  '离开': 'rời khỏi',
  '礼物': 'quà tặng',
  '邻居': 'hàng xóm',
  '留': 'giữ lại, lưu',
  '留学': 'du học',
  '流利': 'lưu loát',
  '旅游': 'du lịch',
  '绿': 'xanh lá',
  '慢': 'chậm',
  '忙': 'bận',
  '每': 'mỗi',
  '妹妹': 'em gái',
  '门': 'cửa',
  '米饭': 'cơm',
  '面包': 'bánh mì',
  '拿': 'cầm, lấy',
  '南': 'phía nam',
  '难过': 'buồn',
  '年级': 'khối lớp',
  '年轻': 'trẻ tuổi',
  '鸟': 'chim',
  '啤酒': 'bia',
  '平时': 'ngày thường',
  '汽车': 'ô tô',
  '铅笔': 'bút chì',
  '请': 'mời, xin',
  '秋': 'mùa thu',
  '裙子': 'váy',
  '然后': 'sau đó',
  '热情': 'nhiệt tình',
  '认为': 'cho rằng',
  '容易': 'dễ dàng',
  '如果': 'nếu',
  '伞': 'ô, dù',
  '声音': 'âm thanh',
  '世界': 'thế giới',
  '试': 'thử',
  '瘦': 'gầy',
  '叔叔': 'chú',
  '舒服': 'thoải mái',
  '树': 'cây',
  '数学': 'toán học',
  '刷牙': 'đánh răng',
  '双': 'đôi',
  '水平': 'trình độ',
  '太阳': 'mặt trời',
  '特别': 'đặc biệt',
  '疼': 'đau',
  '提高': 'nâng cao',
  '体育': 'thể dục',
  '同事': 'đồng nghiệp',
  '同意': 'đồng ý',
  '头发': 'tóc',
  '突然': 'đột nhiên',
  '图': 'bản đồ, tranh',
  '腿': 'chân (cẳng)',
  '完成': 'hoàn thành',
  '为了': 'để, vì',
  '为什么': 'tại sao',
  '位': 'vị (lượng từ敬)',
  '味道': 'mùi vị',
  '温度': 'nhiệt độ',
  '文章': 'bài văn',
  '污染': 'ô nhiễm',
  '习惯': 'thói quen, quen',
  '洗': 'rửa, giặt',
  '洗手间': 'nhà vệ sinh',
  '夏': 'mùa hè',
  '先': 'trước',
  '香': 'thơm',
  '笑': 'cười',
  '校长': 'hiệu trưởng',
  '鞋': 'giày',
  '新闻': 'tin tức',
  '新鲜': 'tươi mới',
  '信': 'thư, tin',
  '信用卡': 'thẻ tín dụng',
  '行李箱': 'vali',
  '兴趣': 'hứng thú',
  '熊猫': 'gấu trúc',
  '需要': 'cần',
  '选择': 'lựa chọn',
  '要求': 'yêu cầu',
  '药': 'thuốc',
  '爷爷': 'ông nội',
  '也': 'cũng',
  '页': 'trang (sách)',
  '饮料': 'đồ uống',
  '游': 'bơi, du ngoạn',
  '游泳': 'bơi lội',
  '远': 'xa',
  '月亮': 'mặt trăng',
  '云': 'mây',
  '咱们': 'chúng ta (gồm người nghe)',
  '脏': 'bẩn',
  '照顾': 'chăm sóc',
  '照片': 'ảnh',
  '照相机': 'máy ảnh',
  '着急': 'sốt ruột',
  '只': 'chỉ (phó từ), con (lượng từ)',
  '只有': 'chỉ có',
  '中': 'giữa, trong',
  '终于': 'cuối cùng',
  '种': 'loại (lượng từ)',
  '周末': 'cuối tuần',
  '主要': 'chủ yếu',
  '注意': 'chú ý',
  '自己': 'bản thân',
  '自行车': 'xe đạp',
  '总是': 'luôn luôn',
  '嘴': 'miệng',
  '最后': 'cuối cùng',
  '作用': 'tác dụng',
  // ===== HSK 3–4 thường gặp =====
  '阿姨': 'dì/cô (gọi phụ nữ trung niên)',
  '矮': 'thấp, lùn',
  '安静': 'yên tĩnh',
  '安全': 'an toàn',
  '把': '(giới từ câu chữ 把)',
  '搬': 'chuyển, dọn',
  '办法': 'cách, biện pháp',
  '办公室': 'văn phòng',
  '帮助': 'giúp đỡ',
  '饱': 'no (ăn no)',
  '表示': 'biểu thị, bày tỏ',
  '表演': 'biểu diễn',
  '冰箱': 'tủ lạnh',
  '才': 'mới (phó từ)',
  '查': 'tra, kiểm tra',
  '差不多': 'gần như, xấp xỉ',
  '尝': 'nếm',
  '场': 'sân, buổi (lượng từ)',
  '超过': 'vượt quá',
  '吵': 'ồn ào, cãi nhau',
  '春': 'mùa xuân',
  '词语': 'từ ngữ',
  '断': 'đứt, gãy',
  '对面': 'đối diện',
  '果汁': 'nước ép',
  '过程': 'quá trình',
  '过去': 'quá khứ, đi qua',
  '哈哈': 'haha (cười)',
  '害怕': 'sợ hãi',
  '森林': 'rừng',
  '永': 'mãi mãi (chữ luyện 8 nét cơ bản)',
};
