// Dữ liệu dịch nghĩa cho Ngữ pháp HSK 3.0 (bản 2025) — trích từ public/app.js
// Các bản đồ này dùng để seed nghĩa tiếng Việt (từng phần) vào bảng grammar trong SQLite.
export const GRAM_CAT_VI: Record<string,string> = {
  '语素': 'Hình vị', '词类': 'Từ loại', '短语': 'Cụm từ', '句子成分': 'Thành phần câu',
  '句子的类型': 'Các kiểu câu', '动作的态': 'Thể của động tác', '特殊表达法': 'Cách diễn đạt đặc biệt',
  '固定格式': 'Cấu trúc cố định', '语段（句群）': 'Đoạn văn (cụm câu)',
};

export const GRAM_SUB_VI: Record<string,string> = {
  '前缀': 'Tiền tố', '后缀': 'Hậu tố', '名词': 'Danh từ', '动词': 'Động từ', '代词': 'Đại từ',
  '数词': 'Số từ', '量词': 'Lượng từ', '副词': 'Phó từ', '介词': 'Giới từ', '连词': 'Liên từ',
  '助词': 'Trợ từ', '叹词': 'Thán từ', '形容词': 'Tính từ', '结构类型': 'Loại kết cấu',
  '主语': 'Chủ ngữ', '谓语': 'Vị ngữ', '宾语': 'Tân ngữ', '定语': 'Định ngữ', '状语': 'Trạng ngữ',
  '补语': 'Bổ ngữ', '句型': 'Kiểu câu', '句类': 'Loại câu', '特殊句型': 'Kiểu câu đặc biệt',
  '复句': 'Câu ghép', '数的表达法': 'Cách đếm số', '时间表示法': 'Cách chỉ thời gian',
  '功能类型': 'Loại chức năng', '固定短语': 'Cụm cố định', '特殊句式': 'Cấu trúc câu đặc biệt',
  '数的表示法': 'Cách chỉ số', '类前缀': 'Tiền tố (biến thể)', '类后缀': 'Hậu tố (biến thể)',
  '简单复句': 'Câu ghép đơn giản', '多重复句': 'Câu ghép nhiều tầng',
};

export const GRAM_DET_VI: Record<string,string> = {
  '方位名词': 'Danh từ phương vị', '能愿动词': 'Động từ năng nguyện', '离合词': 'Từ ly hợp',
  '疑问代词': 'Đại từ nghi vấn', '人称代词': 'Đại từ nhân xưng', '指示代词': 'Đại từ chỉ định',
  '名量词': 'Lượng từ danh', '时量词': 'Lượng từ thời gian', '动量词': 'Lượng từ động',
  '动词重叠': 'Động từ lặp', '形容词重叠': 'Tính từ lặp', '量词重叠': 'Lượng từ lặp',
  '程度副词': 'Phó từ mức độ', '范围副词': 'Phó từ phạm vi', '时间副词': 'Phó từ thời gian',
  '频率副词': 'Phó từ tần suất', '关联副词': 'Phó từ liên hệ', '否定副词': 'Phó từ phủ định',
  '方式副词': 'Phó từ phương thức', '情态副词': 'Phó từ tình thái', '语气副词': 'Phó từ ngữ khí',
  '判断副词': 'Phó từ phán đoán', '数量代词': 'Đại từ số lượng', '复合量词': 'Lượng từ ghép',
  '引出时间、处所': 'Giới từ chỉ thời gian/nơi chốn', '引出方向、路径': 'Giới từ chỉ hướng/đường đi',
  '引出对象': 'Giới từ chỉ đối tượng', '引出原因': 'Giới từ chỉ nguyên nhân',
  '引出施事、受事': 'Giới từ chỉ chủ thể/bị động', '引出凭借、依据': 'Giới từ chỉ phương tiện/căn cứ',
  '引出目的、原因': 'Giới từ chỉ mục đích/nguyên nhân',
  '连接词语或短语': 'Nối từ/cụm từ', '连接词或短语': 'Nối từ/cụm từ', '连接词或者短语': 'Nối từ/cụm từ',
  '连接词或词组': 'Nối từ/cụm từ', '连接词或词组以及分句或句子': 'Nối từ/cụm và vế câu/câu',
  '连接分句或者句子': 'Nối vế câu/câu', '连接分句或句子': 'Nối vế câu/câu',
  '结构助词': 'Trợ từ kết cấu', '动态助词': 'Trợ từ động thái', '语气助词': 'Trợ từ ngữ khí',
  '其他助词': 'Trợ từ khác', '基本结构类型': 'Kiểu kết cấu cơ bản', '其他结构类型': 'Kiểu kết cấu khác',
  '名词性短语': 'Cụm danh từ', '动词性短语': 'Cụm động từ', '形容词性短语': 'Cụm tính từ',
  '结构类型': 'Loại kết cấu', '单句': 'Câu đơn', '陈述句': 'Câu trần thuật', '疑问句': 'Câu nghi vấn',
  '祈使句': 'Câu cầu khiến', '感叹句': 'Câu cảm thán', '问句': 'Câu hỏi',
  '“是”字句1': 'Câu chữ “是” (1)', '“是”字句2': 'Câu chữ “是” (2)', '“是”字句3': 'Câu chữ “是” (3)',
  '“有”字句1': 'Câu chữ “有” (1)', '“有”字句2': 'Câu chữ “有” (2)', '“有”字句3': 'Câu chữ “有” (3)',
  '存现句1': 'Câu tồn tại (1)', '存现句2': 'Câu tồn tại (2)', '存现句3': 'Câu tồn tại (3)',
  '连动句1': 'Câu liên động (1)', '连动句2': 'Câu liên động (2)', '连动句3': 'Câu liên động (3)',
  '双宾语句1': 'Câu song tân (1)', '双宾语句2': 'Câu song tân (2)',
  '比较句1': 'Câu so sánh (1)', '比较句2': 'Câu so sánh (2)', '比较句3': 'Câu so sánh (3)',
  '比较句4': 'Câu so sánh (4)', '比较句5': 'Câu so sánh (5)',
  '“是……的”句1': 'Câu “是…的” (1)', '“是……的”句2': 'Câu “是…的” (2)',
  '兼语句1': 'Câu kiêm ngữ (1)', '兼语句2': 'Câu kiêm ngữ (2)',
  '“把”字句1': 'Câu chữ “把” (1)', '“把”字句2': 'Câu chữ “把” (2)',
  '“把”字句3': 'Câu chữ “把” (3)', '“把”字句4': 'Câu chữ “把” (4)',
  '被动句1': 'Câu bị động (1)', '被动句2': 'Câu bị động (2)', '被动句3': 'Câu bị động (3)',
  '反问句1': 'Câu hỏi ngược (1)', '反问句2': 'Câu hỏi ngược (2)',
  '重动句': 'Câu lặp động từ', '双重否定句': 'Câu phủ định kép',
  '结果补语1': 'Bổ ngữ kết quả (1)', '结果补语2': 'Bổ ngữ kết quả (2)',
  '趋向补语1': 'Bổ ngữ xu hướng (1)', '趋向补语2': 'Bổ ngữ xu hướng (2)', '趋向补语3': 'Bổ ngữ xu hướng (3)',
  '可能补语1': 'Bổ ngữ khả năng (1)', '可能补语2': 'Bổ ngữ khả năng (2)',
  '状态补语1': 'Bổ ngữ trạng thái (1)', '状态补语2': 'Bổ ngữ trạng thái (2)',
  '程度补语1': 'Bổ ngữ mức độ (1)', '程度补语2': 'Bổ ngữ mức độ (2)', '程度补语3': 'Bổ ngữ mức độ (3)',
  '数量补语1': 'Bổ ngữ số lượng (1)', '数量补语2': 'Bổ ngữ số lượng (2)', '数量补语3': 'Bổ ngữ số lượng (3)',
  '完成态': 'Thể hoàn thành', '变化态': 'Thể biến đổi', '进行态': 'Thể đang diễn ra',
  '持续态': 'Thể liên tục', '经历态': 'Thể đã từng',
  '不用关联词语的复句': 'Câu ghép không liên từ', '并列复句': 'Câu ghép đẳng lập',
  '选择复句': 'Câu ghép lựa chọn', '转折复句': 'Câu ghép tương phản', '因果复句': 'Câu ghép nhân quả',
  '条件复句': 'Câu ghép điều kiện', '假设复句': 'Câu ghép giả định', '目的复句': 'Câu ghép mục đích',
  '承接复句': 'Câu ghép nối tiếp', '递进复句': 'Câu ghép tăng tiến', '让步复句': 'Câu ghép nhượng bộ',
  '紧缩复句': 'Câu ghép rút gọn', '解说复句': 'Câu ghép giải thích',
  '四字格': 'Cách nói 4 chữ', '表示排除': 'Biểu thị loại trừ', '其 他': 'Khác', '其他': 'Khác',
  '其他（话语标记）': 'Khác (tiểu từ thoại)',
};

export const GRAM_POINT_VI: Record<string,string> = {
  'hsk1|会、能': 'biết làm / có thể',
  'hsk1|想、要': 'muốn / cần, định',
  'hsk1|可以': 'có thể, được phép',
  'hsk1|名词、代词或名词性短语作主语': 'Chủ ngữ là danh từ, đại từ hoặc cụm danh từ',
  'hsk1|动词或动词性短语、形容词或形容词性短语作谓语': 'Vị ngữ là động từ/cụm động từ, tính từ/cụm tính từ',
  'hsk1|动词+动量补语': 'Động từ + bổ ngữ số lần',
  'hsk1|主谓句1：动词谓语句': 'Câu chủ-vị: vị ngữ động từ',
  'hsk1|主谓句2：形容词谓语句': 'Câu chủ-vị: vị ngữ tính từ',
  'hsk1|主谓句3：名词谓语句': 'Câu chủ-vị: vị ngữ danh từ',
  'hsk1|非主谓句': 'Câu phi chủ-vị',
  'hsk1|（1）是非问句': 'Câu hỏi có/không',
  'hsk1|（2）特指问句': 'Câu hỏi chuyên dùng (từ nghi vấn)',
  'hsk1|（3）正反问句': 'Câu hỏi chính-phản',
  'hsk1|表示等同或类属': 'Biểu thị đồng nhất hoặc loại thuộc',
  'hsk1|表示领有': 'Biểu thị sở hữu',
  'hsk1|（1）所处+是+名词': 'Nơi chốn + 是 + danh từ',
  'hsk1|（2）处所+有+数量短语+名词': 'Nơi chốn + 有 + cụm số lượng + danh từ',
  'hsk1|主语+动词+宾语1+宾语2': 'Chủ ngữ + động từ + tân ngữ 1 + tân ngữ 2',
  'hsk1|……，也……': '…, cũng…',
  'hsk1|……，还……': '…, còn…',
  'hsk1|用动态助词“了1”表示': 'Dùng trợ từ động thái “了” biểu thị',
  'hsk1|用动态助词“了2”表示': 'Dùng trợ từ ngữ khí “了” biểu thị',
  'hsk1|（1）……在/正在+动词': '… đang + động từ',
  'hsk1|（2）……在/正在+动词……+呢': '… đang + động từ… + 呢',
  'hsk1|（3）……呢': '… 呢 (đang làm gì)',
  'hsk1|钱数表示法': 'Cách nói số tiền',
  'hsk1|序数表达法1：第+数词': 'Số thứ tự: 第 + số từ',
  'hsk1|（1）年、月、日、星期表示法': 'Cách nói năm, tháng, ngày, thứ',
  'hsk1|（2）钟点表示法': 'Cách nói giờ',
  'hsk2|AA、A一A、A了A、ABAB': 'Động từ lặp: VV / V一V / V了V / VV',
  'hsk2|（1）专用名量词：条、位、间、名': 'Lượng từ danh chuyên dùng',
  'hsk2|动补短语1': 'Cụm động-bổ',
  'hsk2|用“还是”连接的选择问句': 'Câu hỏi lựa chọn dùng “还是”',
  'hsk2|用“别”的祈使句': 'Câu cầu khiến dùng “别”',
  'hsk2|表示说明或特征': 'Biểu thị giải thích hoặc đặc điểm',
  'hsk2|表示达到': 'Biểu thị đạt tới mức nào đó',
  'hsk2|处所+动词+着(+数量短语)+名词': 'Nơi chốn + động từ + 着 (+ số lượng) + danh từ',
  'hsk2|（1）A比B+形容词': 'So sánh: A hơn B + tính từ',
  'hsk2|（2）A比B+形容词+数量补语/程度补语': 'A hơn B + tính từ + bổ ngữ',
  'hsk2|（3）A有/没有B（+这么/那么）+形容词': 'A có/không bằng B (…thế) + tính từ',
  'hsk2|（4）A比B+动词+得+形容词/A+动词+得+比+B+形容词': 'A VB hơn B',
  'hsk2|强调时间、地点、方式、动作者': 'Nhấn mạnh thời gian, nơi chốn, cách thức, người thực hiện',
  'hsk2|表使令：主语+请/叫/让……+宾语1+动词+宾语2': 'Biểu thị sai khiến',
  'hsk2|主语+动词+给+宾语1+宾语2': 'Chủ ngữ + động từ + 给 + tân ngữ 1 + tân ngữ 2',
  'hsk2|（是）……，还是……': '(Là)…, hay… (lựa chọn)',
  'hsk2|虽然……，但是……': 'Mặc dù…, nhưng…',
  'hsk2|因为……，所以……': 'Vì…, nên…',
  'hsk2|一……就……': 'Hễ… là…',
  'hsk2|动词+着：（1）表示状态的持续': 'Động từ + 着: trạng thái tiếp diễn',
  'hsk2|（2）表示动作的持续': 'Hành động tiếp diễn',
  'hsk2|用动态助词“过”表示': 'Dùng trợ từ “过” (đã từng)',
  'hsk2|序数表示法2：数词+量词': 'Số thứ tự: số + lượng từ',
  'hsk2|（1）用“几”表示概数': 'Dùng “几” chỉ số xấp xỉ',
  'hsk2|（2）数词+多+量词': 'Số + 多 + lượng từ',
  'hsk2|（3）数词+量词+多': 'Số + lượng từ + 多',
  'hsk3|动宾式离合词：放假、见面、结婚、洗澡': 'Từ ly hợp động-tân: nghỉ lễ, gặp mặt, kết hôn, tắm',
  'hsk3|动补式离合词：离开、完成、分开': 'Từ ly hợp động-bổ: rời đi, hoàn thành, chia tách',
  'hsk3|（1）任指用法：①疑问代词+都……②疑问代词+疑问代词': 'Cách dùng phiếm chỉ (bất kỳ ai/đâu/gì)',
  'hsk3|（2）不定指用法': 'Cách dùng chỉ định bất định',
  'hsk3|个个、张张': 'Lượng từ lặp (mỗi/mọi)',
  'hsk3|不A 不 B': 'Không A không B (không…thì không…)',
  'hsk3|除了 ……（以外），……还/也/都……': 'Ngoài… ra, còn/cũng/đều…',
  'hsk3|从……起': 'Từ… trở đi',
  'hsk3|对……来说': 'Đối với… mà nói',
  'hsk3|一……也/都+不/没……': 'Một… cũng không/không có…',
  'hsk3|一点儿也不': 'Không một chút nào',
  'hsk3|越……越……': 'Càng… càng…',
  'hsk3|（在）……以前/以后/前/后': '(Ở) trước/sau…',
  'hsk3|X什么（啊）': 'X…cái gì (không cần)',
  'hsk3|该……了': 'Đến lúc phải… rồi',
  'hsk3|在……上/下/中': 'Ở trên/dưới/trong…',
  'hsk3|多项定语': 'Nhiều định ngữ',
  'hsk3|动词+到/住/走/上': 'Động từ + 到/住/走/上 (bổ ngữ kết quả)',
  'hsk3|（1）表示结果意义：动词+出/起/下': 'Nghĩa kết quả: V + 出/起/下',
  'hsk3|（2）表示动作行为的开始：动词+上/起来': 'Nghĩa bắt đầu: V + 上/起来',
  'hsk3|（3）表示动作行为的持续：动词+下去/下来': 'Nghĩa tiếp tục: V + 下去/下来',
  'hsk3|动词+得/不+动词/形容词': 'Động từ + 得/不 + động từ/tính từ (bổ ngữ khả năng)',
  'hsk3|（1）形容词+得很': 'Tính từ + 得很 (rất…)',
  'hsk3|（2）形容词/动词+极了/坏了': 'Tính từ/động từ + 极了/坏了 (cực kỳ)',
  'hsk3|表示动作结束到某个时间点的间隔时间': 'Khoảng thời gian từ khi kết thúc đến một thời điểm',
  'hsk3|“怎样+动词”的特指问句': 'Câu hỏi dùng “怎样 + động từ”',
  'hsk3|用反问句表示强调：不是……吗？': 'Chẳng phải… sao?',
  'hsk3|（1）主语+把+宾语+动词+在/到+处所': 'S + 把 + O + V + 在/到 + nơi chốn',
  'hsk3|（2）主语+把+宾语1+动词（+给）+宾语2': 'S + 把 + O1 + V (+ 给) + O2',
  'hsk3|（3）主语+把+宾语+动词+结果补语/趋向补语/状态补语': 'S + 把 + O + V + bổ ngữ',
  'hsk3|（1）主语+被+宾语+动词+其他成分': 'S + 被 + O + V + thành phần khác',
  'hsk3|（2）主语+被+动词+其他成分': 'S + 被 + V + thành phần khác',
  'hsk3|“着”表示动作的伴随：动词1+着+动词2': 'V1 + 着 + V2: làm V2 với tư thế/cách V1',
  'hsk3|（1）A比B+更/还+形容词': 'A càng hơn B + tính từ',
  'hsk3|（2）A跟B一样': 'A giống B',
  'hsk3|（3）A跟B一样+形容词': 'A bằng B + tính từ',
  'hsk3|（4）A不比B+形容词': 'A không hơn B + tính từ',
  'hsk3|（5）A比B+多/少/早/晚+动词+数量短语': 'A hơn B về mức/độ/sớm/muộn',
  'hsk3|（1）表示出现：处所词+动词+趋向补语/结果补语+动态助词（了）+数量短语+人/物': 'Sự xuất hiện',
  'hsk3|（2）表示消失：处所词+动词+结果补语+动态助词（了）+数量短语+人/物': 'Sự biến mất',
  'hsk3|强调说话人的看法或态度': 'Nhấn mạnh quan điểm/thái độ người nói',
  'hsk3|主语+动词+宾语+动词+补语': 'S + V + O + V + bổ ngữ (câu lặp động từ)',
  'hsk3|先……，再/然后……': 'Trước…, rồi/sau đó…',
  'hsk3|或者……，或者……': 'Hoặc…, hoặc…',
  'hsk3|一会儿……，一会儿……': 'Lúc…, lúc…',
  'hsk3|又……，又……': 'Vừa…, vừa…',
  'hsk3|一边……，一边……': 'Vừa…, vừa…',
  'hsk3|不但……，而且……': 'Không những…, mà còn…',
  'hsk3|虽然……，可是……': 'Mặc dù…, nhưng…',
  'hsk3|如果……，就……': 'Nếu…, thì…',
  'hsk3|……的话，就……': 'Nếu (như)…, thì…',
  'hsk3|只有……，才……': 'Chỉ khi…, mới…',
  'hsk3|只要……，就……': 'Chỉ cần…, là…',
  'hsk3|为了……，……': 'Để… (mục đích)',
  'hsk3|……了……（就）……': '…rồi… (liền)…',
  'hsk3|（1）用“大概”表示概数': 'Dùng “大概” chỉ số xấp xỉ',
  'hsk3|（2）相邻数词连用表示概数': 'Số liền nhau biểu thị xấp xỉ',
  'hsk4|十分、更加、稍、稍微、尤其、多么': 'Phó từ mức độ (rất, càng, hơn, đặc biệt)',
  'hsk4|（1）主语+把+宾语+动词（+一/了）+动词': 'S + 把 + O + V (一/了) + V',
  'hsk4|（2）主语+把+宾语+动词+了': 'S + 把 + O + V + 了',
  'hsk4|（3）主语+把+宾语+动词+动量补语/时量补语': 'S + 把 + O + V + bổ ngữ số lần/thời gian',
  'hsk4|（4）主语+把+宾语+状语+动词': 'S + 把 + O + trạng ngữ + V',
  'hsk4|主语+叫/让+宾语+动词+其他成分': 'S + 叫/让 + O + V + thành phần khác (bị động)',
  'hsk4|（1）表爱憎义：主语+表扬/批评+宾语1+动词+宾语2': 'Biểu thị yêu/ghét',
  'hsk4|（2）表称谓或认定义：主语+收/选+宾语1+做/当/为+宾语2': 'Biểu thị xưng hô/nhận định',
  'hsk4|（3）表致使：主语+使/让+人称代词+动词短语': 'Biểu thị khiến cho',
  'hsk4|（1）A不如B（+形容词）': 'A không bằng B (+ tính từ)',
  'hsk4|（2）跟……相比': 'So với…',
  'hsk4|用双重否定表示强调': 'Phủ định kép để nhấn mạnh',
  'hsk4|不是……，而是……': 'Không phải…, mà là…',
  'hsk4|既……，又/也……': 'Vừa…, vừa…',
  'hsk4|一方面……，另一方面……': 'Một mặt…, mặt khác…',
  'hsk4|首先……，其次……': 'Trước hết…, kế đến…',
  'hsk4|首先……，然后……': 'Trước hết…, sau đó…',
  'hsk4|……，于是……': '…, vì vậy…',
  'hsk4|……,甚至……': '…, thậm chí…',
  'hsk4|不仅/不光……，还/而且……': 'Không chỉ…, mà còn…',
  'hsk4|……，并且……': '…, đồng thời…',
  'hsk4|连……也/都……，……更……': 'Ngay cả… cũng…, …lại càng…',
  'hsk4|不是……，就是……': 'Không…, thì…',
  'hsk4|尽管……，但是/可是……': 'Dù…, nhưng…',
  'hsk4|……，然而……': '…, tuy nhiên…',
  'hsk4|……，不过……': '…, nhưng mà…',
  'hsk4|……X是X，就是/不过……': '…X là X, nhưng…',
  'hsk4|……，否则……': '…, nếu không thì…',
  'hsk4|要是……，就……': 'Nếu…, thì…',
  'hsk4|不管……，都/也……': 'Dù…, đều/cũng…',
  'hsk4|无论……，都/也……': 'Dù…, đều/cũng…',
  'hsk4|既然……，就……': 'Đã…, thì…',
  'hsk4|（由于）……，因此……': '(Do)…, vì vậy…',
  'hsk4|……，好……': '…, để… (mục đích)',
  'hsk4|即使……，也……': 'Cho dù…, cũng…',
  'hsk4|就是……，也……': 'Cho dù…, cũng…',
  'hsk4|不……也……': 'Không… cũng…',
  'hsk4|概数表示法3：数词+来+量词': 'Số + 来 + lượng từ (khoảng)',
  'hsk4|用“大约、左右、前后”表示概数': 'Dùng 大约/左右/前后 chỉ xấp xỉ',
  'hsk4|一+量词+比+一+量词': 'Ngày càng (mỗi lúc một…)',
  'hsk4|在……方面': 'Về phương diện…',
  'hsk4|够……的': 'Đủ… đấy',
  'hsk4|拿……来说': 'Lấy… làm ví dụ',
  'hsk4|再也不/没……': 'Sẽ không bao giờ… nữa',
  'hsk4|怎么都/也+不/没……': 'Thế nào cũng không…',
  'hsk4|为了……而……': 'Vì… mà…',
  'hsk4|动词+一X是一X': 'Động từ + X là X (bay giờ lúc nào)',
  'hsk4|（没）有什么（好）X的': '(Không) có gì (để) mà X',
  'hsk4|X是X，Y是Y': 'X là X, Y là Y (không lẫn lộn)',
  'hsk4|X也得X，不X也得X': 'X được, không X cũng phải X (bắt buộc)',
  'hsk4|X就是了': 'Cứ X là được',
  'hsk4|还X呢': 'Còn X đấy (nói mỉa)',
  'hsk4|你X你的吧': 'Bạn cứ X việc của bạn đi',
  'hsk4|让/叫你X你就X': 'Bảo X thì cứ X',
  'hsk4|说什么/怎么（着）也得X': 'Thế nào cũng phải X',
  'hsk4|X就X（点儿）吧': 'X thì X (một chút) thôi',
  'hsk4|X是X': 'X là X',
  'hsk4|形容词/心理动词+死了/厉害': 'Tính từ/động từ tâm lý + ghê/chết',
  'hsk4|动词+得/不+了': 'Động từ + 得/不 + 了 (bổ ngữ khả năng)',
  'hsk4|难道……吗？': 'Chẳng lẽ… sao?',
  'hsk4|由疑问代词构成的反问句': 'Câu hỏi ngược dùng đại từ nghi vấn',
  'hsk5|动词+得/不得': 'Động từ + 得/不得 (không… được)',
  'hsk5|（1）表示存在、具有：主语+有+着+宾语': 'Biểu thị tồn tại/sở hữu 有+着',
  'hsk5|（2）表示附着：主语+动词+有+宾语': 'Biểu thị gắn kèm: V + 有',
  'hsk5|（1）主语+把+宾语+一+动词': 'S + 把 + O + 一 + V',
  'hsk5|（2）主语+把+宾语1+动词+宾语2': 'S + 把 + O1 + V + O2',
  'hsk5|A+形容词+B+数量补语': 'A + tính từ + B + bổ ngữ số lượng',
  'hsk5|主语+被/叫/让+宾语+给+动词+其他成分': 'S + 被/叫/让 + O + 给 + V + ...',
  'hsk5|……，便……': '…, liền…',
  'hsk5|或是……，或是……': 'Hoặc…, hoặc…',
  'hsk5|一旦……，就……': 'Một khi…, thì…',
  'hsk5|假如……，（就）……': 'Giả sử…, (thì)…',
  'hsk5|万一……，（就）……': 'Ngộ nhỡ…, (thì)…',
  'hsk5|……，要不然/不然……': '…, nếu không thì…',
  'hsk5|……，因而……': '…, do đó…',
  'hsk5|……，可见……': '…, có thể thấy…',
  'hsk5|哪怕……，也……': 'Dẫu…, cũng…',
  'hsk5|不但不/不但没有……，反而……': 'Không những không…, mà ngược lại…',
  'hsk5|不是……，还/还是……': 'Không phải…, mà còn…',
  'hsk5|……，为的是……': '…, để mà…',
  'hsk5|没有……就没有……': 'Không có…, sẽ không có…',
  'hsk5|不……不……': 'Không… không… (câu ghép rút gọn)',
  'hsk5|再……也……': 'Dù có… cũng…',
  'hsk6|人家': 'Người ta',
  'hsk6|不禁、赶忙、特地、特意、偷偷': 'Phó từ (không nén được, vội, cố ý, lén)',
  'hsk6|未必': 'Chưa chắc',
  'hsk6|恰好、倒是、干脆、明明、总算': 'Phó từ ngữ khí (đúng lúc, ngược lại, dứt khoát)',
  'hsk6|所': 'Trợ từ “所”',
  'hsk6|A这A那': 'A này A kia',
  'hsk6|左A右B': 'Trái A phải B',
  'hsk6|到……为止': 'Cho đến…, kết thúc',
  'hsk6|动词/形容词+透+了': 'Động từ/tính từ + 透 + 了 (rất, toát)',
  'hsk6|（1）主语（非生物体）+把+宾语+动词+其他成分': 'Chủ ngữ (không phải người) + 把 + O + V',
  'hsk6|（2）主语+把+宾语（施事）+动词+其他成分': 'S + 把 + O (chủ thể hành động) + V',
  'hsk6|一时……一时……': 'Lúc…, lúc…',
  'hsk6|要么……，要么……': 'Hoặc…, hoặc…',
  'hsk6|虽……，但/可/却/也……': 'Dù…, nhưng/ngược/cũng…',
  'hsk6|凡是……，都……': 'Phàm là…, đều…',
  'hsk6|除非……，才……': 'Trừ phi…, mới…',
  'hsk6|除非……，否则/不然……': 'Trừ phi…, nếu không thì…',
  'hsk6|就算……，也……': 'Cho dù…, cũng…',
  'hsk6|……，以便……': '…, để (mục đích)…',
  'hsk79|动词': 'Động từ đặc biệt',
  'hsk79|巴不得、并非、除外、犯不着': 'Động từ đặc biệt (mong cho lắm, chẳng phải, ngoại trừ)',
  'hsk79|通常、时常、老是': 'Phó từ tần suất',
  'hsk79|宁可、宁愿': 'Thà…, thà…',
  'hsk79|非得……才……': 'Bắt buộc…, mới…',
  'hsk79|任……也……': 'Cho dù…, cũng…',
  'hsk79|无论……与否，都……': 'Dù… hay không, đều…',
  'hsk79|别说……，都/也……': 'Đừng nói…, đều/cũng…',
  'hsk79|……，更不用说……了': '…, nói gì đến…',
  'hsk79|……尚且……，（更）何况……': '…đã vậy…, huống chi…',
  'hsk79|为（了）……起见，……': 'Vì (để)… cho (an toàn)…',
  'hsk79|……，以……': '…, để (mục đích trang trọng)…',
  'hsk79|与……相比': 'So với…',
  'hsk79|一……就……': 'Hễ…, là…',
  'hsk79|宁可/宁愿……，也不……': 'Thà…, còn hơn…',
  'hsk79|与其……，宁愿/宁可……': 'Thà…, còn hơn…',
  'hsk79|别看……，……': 'Đừng tưởng…, (thực ra)…',
  'hsk79|虽说……，但/可……': 'Tuy nói…, nhưng…',
  'hsk79|幸亏/幸好……，不然/否则……': 'May mà…, nếu không…',
  'hsk79|纵然/纵使……，也……': 'Cho dù…, cũng…',
  'hsk79|（因）……，故……': '(Vì)…, nên (trang trọng)…',
  'hsk79|……，以至（于）……': '…, đến mức…',
  'hsk79|因……而……': 'Vì… mà…',
  'hsk79|视……而定': 'Tùy… mà định',
  'hsk79|不外/不过/只是……罢了/而已': 'Chỉ (là)… mà thôi',
  'hsk79|鉴于1': 'Vì (xét thấy)…',
};

